apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: logstash-pipelines
data:
{% macro inc(str) %}{% include str %}{% endmacro %}
  logstash.conf: |
{{ inc('6_logstash/logstash.conf')|indent(first=true) }}
